package io.codekoll.cli;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import io.codekoll.api.Rule;
import io.codekoll.api.RulePack;
import io.codekoll.engine.RuleRegistry;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;
import org.junit.jupiter.api.Test;

/**
 * The registry is the only source of truth for how many rules and packs exist. Two places restate
 * it and cannot be checked by the compiler: the two registration lists a rule must appear in, and
 * the counts written into the documentation. Both have drifted before.
 */
class RegistryConsistencyTest {

  private static final Path REPO_ROOT = Path.of("..").toAbsolutePath().normalize();

  private static final List<Rule> RULES = RuleRegistry.loadAll();

  private static String read(String relative) throws IOException {
    return Files.readString(REPO_ROOT.resolve(relative), StandardCharsets.UTF_8);
  }

  /**
   * A rule registered in only one list loads under one packaging and silently not the other: the
   * module path uses {@code module-info}, the shaded jar uses {@code META-INF/services}.
   */
  @Test
  void moduleInfoAndServicesRegisterTheSameRules() throws IOException {
    Matcher provides = Pattern.compile("provides\\s+io\\.codekoll\\.api\\.Rule\\s+with([^;]+);")
        .matcher(read("codekoll-rules/src/main/java/module-info.java"));
    assertTrue(provides.find(), "module-info.java must declare the Rule service");
    Set<String> declared = Arrays.stream(provides.group(1).split(","))
        .map(String::trim).filter(s -> !s.isEmpty())
        .collect(Collectors.toCollection(LinkedHashSet::new));

    Set<String> services = read("codekoll-rules/src/main/resources/META-INF/services/io.codekoll.api.Rule")
        .lines().map(String::trim).filter(s -> !s.isEmpty() && !s.startsWith("#"))
        .collect(Collectors.toCollection(LinkedHashSet::new));

    assertEquals(services, declared, "module-info provides and META-INF/services must agree");
    assertEquals(RULES.size(), services.size(), "every registered rule must load");
  }

  /** Counts in prose go stale silently; the badge said 106 rules while 110 shipped. */
  @Test
  void documentedRuleAndPackCountsMatchTheRegistry() throws IOException {
    int rules = RULES.size();
    long packs = RULES.stream().map(Rule::pack).distinct().count();
    String packWord = numberWord(packs);

    String readme = read("README.md");
    assertTrue(readme.contains("rules-" + rules + "-blue"), "README rules badge must say " + rules);
    assertTrue(readme.contains("examples-" + rules + "%2F" + rules), "README examples badge");
    assertTrue(readme.contains(rules + " rules in " + packWord + " packs"),
        "README must say " + rules + " rules in " + packWord + " packs");

    assertTrue(read("SPEC.md").contains("Rules are grouped into " + packWord + " packs."),
        "SPEC section 4 pack count");
    assertTrue(read("docs/RULES.md").contains(rules + " rules."),
        "docs/RULES.md is generated by --catalog and must be regenerated with the catalog");

    for (RulePack pack : RULES.stream().map(Rule::pack).distinct().toList()) {
      long inPack = RULES.stream().filter(rule -> rule.pack() == pack).count();
      assertTrue(read("docs/RULES.md").contains("## " + pack.id() + " (" + inPack + ")"),
          "docs/RULES.md must list " + pack.id() + " with " + inPack + " rules");
    }
  }

  /** Small and fixed: the documentation spells these counts out, so the test has to as well. */
  private static String numberWord(long n) {
    return switch ((int) n) {
      case 9 -> "nine";
      case 10 -> "ten";
      case 11 -> "eleven";
      case 12 -> "twelve";
      default -> throw new IllegalStateException("add the word for " + n + " packs");
    };
  }
}
