package io.codekoll.workspace;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystems;
import java.nio.file.FileVisitResult;
import java.nio.file.FileVisitor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.PathMatcher;
import java.nio.file.attribute.BasicFileAttributes;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Selects the {@code .java} files to analyze under a set of roots.
 *
 * <p>Directories are pruned during the walk rather than filtered afterwards, which is what keeps
 * {@code node_modules} and a vendored {@code .m2/repository} from costing anything.
 */
final class FileSelector {

  /**
   * Directory names never walked into. These are build outputs, VCS metadata and dependency
   * caches — analyzing them means reporting findings against files nobody wrote and, worse,
   * against stale copies of files that were since fixed.
   */
  private static final Set<String> EXCLUDED_DIRS = Set.of(
      "target", "build", "out", "bin", "dist",
      ".git", ".svn", ".hg", ".gradle", ".m2", ".mvn", ".idea", ".vscode", ".settings",
      "node_modules", "__pycache__", ".venv", "venv");

  /** Directory names under a source root whose contents are machine-written. */
  private static final Set<String> GENERATED_DIRS = Set.of(
      "generated", "generated-sources", "generated-test-sources", "gen");

  /** Marker text in the first few lines of a machine-written source file. */
  private static final List<String> GENERATED_MARKERS = List.of(
      "@generated", "generated by", "do not edit", "this file is automatically generated");

  private static final int GENERATED_MARKER_LINES = 5;

  /**
   * True when a directory with this name is never walked into. Shared with source-root scanning
   * so that both passes agree on what is build output — disagreeing would mean discovering a
   * source root inside {@code target/} and then finding no files in it.
   */
  static boolean isExcludedDirName(String name) {
    return EXCLUDED_DIRS.contains(name) || GENERATED_DIRS.contains(name);
  }

  private final Path repoRoot;
  private final WorkspaceOptions options;
  private final GitIgnoreMatcher gitignore;
  private final List<String> diagnostics;
  private final List<PathMatcher> excludeMatchers;

  FileSelector(Path repoRoot, WorkspaceOptions options, GitIgnoreMatcher gitignore,
      List<String> diagnostics) {
    this.repoRoot = repoRoot;
    this.options = options;
    this.gitignore = gitignore;
    this.diagnostics = diagnostics;
    this.excludeMatchers = new ArrayList<>();
    for (String glob : options.excludes()) {
      excludeMatchers.add(FileSystems.getDefault().getPathMatcher("glob:" + glob));
    }
  }

  /** Returns the sorted, de-duplicated {@code .java} files under {@code root}. */
  List<Path> select(Path root) {
    Collector collector = new Collector();
    try {
      Files.walkFileTree(root, Set.of(), Integer.MAX_VALUE, collector);
    } catch (IOException e) {
      diagnostics.add("could not walk " + rel(root) + ": " + e.getMessage());
    }
    List<Path> files = new ArrayList<>(collector.found);
    files.sort(Path::compareTo);
    return files;
  }

  private String rel(Path path) {
    Path absolute = path.toAbsolutePath().normalize();
    Path base = repoRoot.toAbsolutePath().normalize();
    String text = absolute.startsWith(base)
        ? base.relativize(absolute).toString()
        : absolute.toString();
    return text.replace('\\', '/');
  }

  private boolean excludedByGlob(Path file) {
    Path relative = Path.of(rel(file));
    for (PathMatcher matcher : excludeMatchers) {
      if (matcher.matches(relative) || matcher.matches(file)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Reads the first few lines looking for a generator banner. Worth the read: generated sources
   * outnumber hand-written ones in some repositories and every finding in them is unactionable.
   */
  private boolean looksGenerated(Path file) {
    try (var reader = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
      for (int i = 0; i < GENERATED_MARKER_LINES; i++) {
        String line = reader.readLine();
        if (line == null) {
          return false;
        }
        String lower = line.toLowerCase(Locale.ROOT);
        for (String marker : GENERATED_MARKERS) {
          if (lower.contains(marker)) {
            return true;
          }
        }
      }
    } catch (IOException e) {
      // Unreadable or not UTF-8: let the compiler be the one to complain about it.
      return false;
    }
    return false;
  }

  /** Walks a tree, pruning excluded directories and collecting analyzable sources. */
  private final class Collector implements FileVisitor<Path> {

    private final List<Path> found = new ArrayList<>();
    private final Set<Path> visitedDirs = new HashSet<>();

    @Override
    public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) {
      Path name = dir.getFileName();
      if (name != null) {
        String text = name.toString();
        if (EXCLUDED_DIRS.contains(text) || GENERATED_DIRS.contains(text)) {
          return FileVisitResult.SKIP_SUBTREE;
        }
      }
      if (attrs.isSymbolicLink() || !visitedDirs.add(dir.toAbsolutePath().normalize())) {
        // Guards against symlink loops without following links out of the repository.
        return FileVisitResult.SKIP_SUBTREE;
      }
      if (options.useGitignore() && gitignore.isIgnored(rel(dir), true)) {
        return FileVisitResult.SKIP_SUBTREE;
      }
      return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) {
      Path name = file.getFileName();
      if (name == null || !name.toString().endsWith(".java")) {
        return FileVisitResult.CONTINUE;
      }
      if ("module-info.java".equals(name.toString())) {
        return FileVisitResult.CONTINUE;
      }
      if (attrs.size() > options.maxFileBytes()) {
        diagnostics.add("skipped " + rel(file) + ": " + attrs.size()
            + " bytes exceeds the " + options.maxFileBytes() + "-byte limit");
        return FileVisitResult.CONTINUE;
      }
      if (options.useGitignore() && gitignore.isIgnored(rel(file), false)) {
        return FileVisitResult.CONTINUE;
      }
      if (excludedByGlob(file) || looksGenerated(file)) {
        return FileVisitResult.CONTINUE;
      }
      found.add(file.toAbsolutePath().normalize());
      return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult visitFileFailed(Path file, IOException exc) {
      diagnostics.add("could not read " + rel(file) + ": " + exc.getMessage());
      return FileVisitResult.CONTINUE;
    }

    @Override
    public FileVisitResult postVisitDirectory(Path dir, @org.jspecify.annotations.Nullable
        IOException exc) {
      return FileVisitResult.CONTINUE;
    }
  }
}
